---
- name: HCP Vault Integration Example
  hosts: localhost
  tasks:
  # Gets secret value
    - name: Lookup with hashi_vault
      ansible.builtin.set_fact:
        secret_1: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/aap/test:lookup_toppings') }}"
      no_log: true

    # This is only for testing, remove for production
    - name: Display the secret with hashi_vault
      ansible.builtin.debug:
        msg: "{{ secret_1 }}"

     # If a secret has many subkeys, one task can get them all at once
    - name: return secrets as a dict (default)
      ansible.builtin.set_fact:
        my_secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/aap/funtest') }}"
      no_log: true
    - name: Show one specific subkey from a secret
      ansible.builtin.debug:
        msg: "{{ my_secrets['subkey_burger'] }}"
    - name: Loop through all subkeys within a secret
      ansible.builtin.debug:
        msg: "Secret '{{ item.key }}' has value '{{ item.value }}'"
      loop: "{{ my_secrets | dict2items }}"

# Gets secret value and metadata
    - name: Lookup with vault_kv2_get
      ansible.builtin.set_fact:
        secret_2: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/test') }}"
      no_log: true

    # This is only for testing, remove for production
    - name: Display the secret with vault_kv2_get
      ansible.builtin.debug:
        msg: "{{ secret_2 }}"
